version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asap-auth
    ports:
      - "8041:5432"
    restart: unless-stopped

networks:
  asap-auth:
    driver: bridge